version: '3'

dotenv: ['.env']

tasks:
  init:
    desc: Initial setup for whole project
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: dependencies
      - task: build

  dependencies:
    desc: Install dependencies for your OS
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - command -v bash
    cmds:
      - echo "Installing dependencies for this project"
      - bash scripts/dependencies.sh

  build:
    desc: Creates an optimized production build of your application
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - command -v platformio
    cmds:
      - echo "Building project"
      - platformio run

  upload:
    desc: Upload compiled code into the device
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - command -v platformio
    cmds:
      - task: wifi_values_replace
      - echo "Uploading project"
      - platformio run --target upload
      - task: debug

  wifi_values_replace:
    silent: true
    desc: it will substitute values from main.cpp file with .env values
    cmds:
      - sed -i '' 's/const char\* ssid =.*/const char* ssid = "{{.WIFI_SSID}}";/' ./src/main.cpp
      - sed -i '' 's/const char\* password =.*;/const char* password = "{{.WIFI_PASSWORD}}";/' ./src/main.cpp

  debug:
    desc: Debug mode for printing out logs
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - command -v platformio
    cmds:
      - echo "Debug mode"
      - platformio device monitor

  update_port:
    desc: Update the port for the device
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - command -v sed
      - command -v ls
    cmds:
      - |
        usb_port=$(find /dev  -name '*usb*' 2> /dev/null | tail -n 1)
        sed -i '' "s|upload_port = .*|upload_port = $usb_port|g" platformio.ini
        echo "Port updated to $usb_port"
